on:
  push:
    tags:
      - '*'
    branches: [ master ]

name: Create release from tag

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install setuptools wheel twine

      - name: Build
        run: |
          python setup.py sdist bdist_wheel

          #- name: Publish
          #  env:
          #    TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          #    TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          #  run: twine upload dist/*
      
      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls dist
          set -x
          (echo ${GITHUB_REF##*/}; echo; git cherry -v $(git describe --abbrev=0 HEAD^) | cut -d" " -f3-) > CHANGELOG
          assets=()
          for tgz in ./dist/*.tar.gz; do
            assets+=("-a" "$tgz")
          done
          hub release create "${assets[@]}" -F CHANGELOG "${GITHUB_REF##*/}"
